name: fastq2tracks
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - bowtie2>=2.5
  - samtools>=1.17
  - bedtools>=2.31
  - trim-galore>=0.6.10
  - fastqc>=0.12
  - macs2>=2.2.9
  - multiqc>=1.18
  - ucsc-bedgraphtobigwig
  - r-base>=4.3
  - bioconductor-chipqc
  - bioconductor-diffbind
  - bioconductor-biocparallel
  - bioconductor-genomicalignments
  - bioconductor-rtracklayer
  - r-ggplot2
  - r-dplyr
  - picard>=3.1
