#!/usr/bin/env python3
"""Parse an ATACseq2tracks configuration without executing shell code."""

from __future__ import annotations

import argparse
import csv
import re
import shlex
import sys
from pathlib import Path
from typing import Optional, Set


ASSIGNMENT = re.compile(r"^([A-Z][A-Z0-9_]*)\s*=\s*(.*)$")
PATH_KEYS = {"SAMPLESHEET", "OUTPUT_DIR"}
OPERATIONAL_KEYS = {"TOTAL_CPU_BUDGET", "RESOURCE_CHECK_MODE"}


def parse_file(path: Path, allowed: Optional[Set[str]] = None) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = ASSIGNMENT.fullmatch(stripped)
        if not match:
            raise ValueError(f"{path}:{line_number}: expected KEY=VALUE")
        key, expression = match.groups()
        if allowed is not None and key not in allowed:
            raise ValueError(f"{path}:{line_number}: unknown configuration key: {key}")
        if key in values:
            raise ValueError(f"{path}:{line_number}: duplicate configuration key: {key}")
        try:
            tokens = shlex.split(expression, comments=True, posix=True)
        except ValueError as error:
            raise ValueError(f"{path}:{line_number}: {error}") from error
        if len(tokens) > 1:
            raise ValueError(f"{path}:{line_number}: quote values containing spaces")
        value = tokens[0] if tokens else ""
        # shlex removes quotes but does not expand expressions. Reject syntax that
        # could be interpreted if the resolved file is later sourced by helpers.
        if any(token in value for token in ("$", "`", ";", "|", "<", ">", "\n", "\r")):
            raise ValueError(f"{path}:{line_number}: shell expressions are not permitted in {key}")
        values[key] = value
    return values


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--template", required=True, type=Path)
    parser.add_argument("--shell-output", required=True, type=Path)
    parser.add_argument("--tsv-output", required=True, type=Path)
    args = parser.parse_args()

    try:
        template = parse_file(args.template)
        allowed = set(template) | OPERATIONAL_KEYS
        supplied = parse_file(args.config, allowed)
    except (OSError, UnicodeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    # Preserve v4.2.0 behavior: a user configuration remains authoritative.
    # Template values are used only for newly introduced operational settings.
    user_keys = set(supplied)
    supplied.setdefault("TOTAL_CPU_BUDGET", "0")
    supplied.setdefault("RESOURCE_CHECK_MODE", "warn")
    config_dir = args.config.resolve().parent
    for key in PATH_KEYS:
        value = supplied.get(key, "")
        if value and not Path(value).is_absolute():
            supplied[key] = str((config_dir / value).resolve())

    missing = [key for key in ("SAMPLESHEET", "OUTPUT_DIR") if not supplied.get(key)]
    if missing:
        print(f"ERROR: required configuration key(s) missing: {', '.join(missing)}", file=sys.stderr)
        return 2

    args.shell_output.parent.mkdir(parents=True, exist_ok=True)
    args.tsv_output.parent.mkdir(parents=True, exist_ok=True)
    with args.shell_output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by resolve_config.py; safe literal assignments only.\n")
        handle.writelines(f"{key}={shell_quote(value)}\n" for key, value in supplied.items())
    with args.tsv_output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(("key", "value", "source"))
        for key, value in supplied.items():
            writer.writerow((key, value, "user" if key in user_keys else "operational_default"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
